site_name: 'test-ci'
site_description: 'Main documentation for the test-ci'
repo_url: https://github.com/silverkeytech/test-ci
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'
