name: test-ci-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main
  workflow_dispatch:  

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
          
      - name: Login to Gitea Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GITEA_REGISTRY }}
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_PAT }}

      - name: Build and push to Gitea Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.GITEA_REGISTRY }}/silverkeytech/test-ci:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3

      - name: Modify values file
        shell: bash
        run: |
          echo 
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/test-ci/prod.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit '

      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password   ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync test-ci
